uclibs/application_portfolio

.gitignore
.rubocop_todo.yml
Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/controllers/application_controller.rb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/front/index.html.erb
app/views/layouts/application.html.erb
config/routes.rb
spec/factories/users.rb
spec/rails_helper.rb
spec/routing/front_routing_spec.rb
spec/views/index.html.erb_spec.rb

Fixes #19 #22 #23 #24
1) Fixed the deprecation warning of factory_girl_rails. Updated the gem and is now "factory_bot_rails"
2) Set the login route to /dashboard after the user logins.
3) Fixed the width of logout button.
4) Added a layout to entire application in "application.html.erb"

Add Bootstrap theme and layout

---

Gemfile
Gemfile.lock
app/models/user.rb
db/migrate/20191122170710_add_roles_to_users.rb
db/schema.rb

Fixes #21 
1) Enabled user authorization by installing "Petergate" gem (https://github.com/elorest/petergate) 2) Petergate gem has "user" role which can be used as "viewer" role. So added only "admin" and "editor" roles.

Install and Configure User Abilities

---

.rubocop_todo.yml
app/assets/stylesheets/application.scss
app/assets/stylesheets/software_records.scss
app/controllers/front_controller.rb
app/controllers/software_records_controller.rb
app/controllers/users_controller.rb
app/helpers/software_records_helper.rb
app/views/devise/sessions/new.html.erb
app/views/front/about.html.erb
app/views/front/contact.html.erb
app/views/front/dashboard.html.erb
app/views/front/index.html.erb
app/views/front/new.html.erb
app/views/front/search.html.erb
app/views/layouts/software_records.html.erb
app/views/shared/_dashboard_header.html.erb
app/views/software_records/_form.html.erb
app/views/software_records/index.html.erb
app/views/users/index.html.erb
spec/controllers/software_records_controller_spec.rb
spec/helpers/software_records_helper_spec.rb
spec/views/software_records/edit.html.erb_spec.rb
spec/views/software_records/index.html.erb_spec.rb

Fixes #77 #78 #80 #81 #84 #85 
- Limited fields for new/edit Software Record form for manager.
- Limited fields for new/edit Software Record form for owner.
- Added more fields on Software Records index page.
- Added more fields in search feature results.
- Replaced the landing page image.

Add more fields Software Records

---

Gemfile
Gemfile.lock
app/models/user.rb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/front/profile.html.erb
config/environments/development.rb
config/environments/production.rb
config/initializers/devise.rb
spec/controllers/users_controller_spec.rb
spec/factories/users.rb
spec/views/front/profile.html.erb_spec.rb

Fixes #108 #110 #111 #112 
- Removed 'Cancel my account' in devise.
- Fixed the chartkick error for "Vendor Records" graph. (due to gem update).
- Increased the minimum password length for devise.
- Customized the password reset email.

Minor bug fixes and UX edits

---

Gemfile
Gemfile.lock
app/assets/stylesheets/software_records.scss
app/controllers/software_records_controller.rb
app/models/user.rb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/front/profile.html.erb
app/views/layouts/software_records.html.erb
app/views/software_records/index.html.erb
config/environments/development.rb
config/environments/production.rb
config/initializers/devise.rb
spec/controllers/users_controller_spec.rb
spec/factories/users.rb
spec/views/front/profile.html.erb_spec.rb
spec/views/software_records/index.html.erb_spec.rb

Fixes #109 
- Added a filter on software records index page.
- Filter based on Software Type and Vendor Records.
- Updated gems to resolve vulnerabilities

Filter on Software Records

---

app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/registrations/new.html.erb
config/environments/development.rb

Fixes #122 
- Generated the URL for the "Forgot Password" mailer.
- Converted the relative path in Signup page to absolute path.

Production Bugs

---

app/controllers/software_records_controller.rb

Fixes #120 
Fixes a filtering bug in Software Records index page.

Filter software records bug fix

---

.rubocop_todo.yml
app/controllers/software_records_controller.rb
app/helpers/software_records_helper.rb
app/mailers/new_user_signup_mailer.rb
app/models/software_record.rb
app/models/user.rb
app/views/front/dashboard.html.erb
app/views/front/new.html.erb
app/views/new_user_signup_mailer/new_user_signup_mail.html.erb
app/views/new_user_signup_mailer/new_user_signup_mail.text.erb
app/views/software_records/_form.html.erb
app/views/software_records/show.html.erb
spec/controllers/software_records_controller_spec.rb
spec/mailers/new_user_signup_mailer_spec.rb
spec/mailers/previews/new_user_signup_preview.rb
spec/models/software_record_spec.rb
spec/views/front/dashboard.html.erb_spec.rb
spec/views/software_records/show.html.erb_spec.rb

Fixes #134 #135 #136 
- Added a new Status field for Software Records (In Upgrade).
- Restricted "Created by" field only for admins.
- Sorted the Vendor Records and Software Types for dropdowns.

New Status Field

---

.circleci/config.yml
.coveralls.yml
Gemfile
Gemfile.lock
spec/spec_helper.rb

Integrate coveralls with circleci

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/software_records.scss
app/views/front/dashboard.html.erb
app/views/front/search.html.erb
app/views/software_records/index.html.erb
app/views/software_types/index.html.erb
app/views/users/index.html.erb
app/views/vendor_records/index.html.erb

Fixes #163 
- Left justified the index pages on software records columns.

Left Justify index page columns

---

app/views/front/dashboard.html.erb
app/views/software_records/_form.html.erb
load_records.rb

Fixes #190 #191 
- Fixed the multi-valued field bug of different roles of users
- Added back the pills on the dashboard for In Design/In Development/Upgrade

Multivalued field role based bug fix

---

app/assets/stylesheets/software_records.scss
app/views/software_records/_change_management.html.erb
app/views/software_records/_form.html.erb
app/views/software_records/_general.html.erb
app/views/software_records/_server_environment.html.erb
app/views/software_records/_upgrade_history.html.erb
app/views/software_records/show.html.erb
db/schema.rb
spec/views/software_records/edit.html.erb_spec.rb
spec/views/software_records/show.html.erb_spec.rb

Resolves #206 
Add tab form/record structure to #edit and #show view for Software Records
---

Set up tabs for software record

---

db/seeds.rb

Resolves #217  
Create dummy seed data for all record types.

Expand db seeds

---

app/controllers/software_records_controller.rb

Fixes blind sql injection.

---

app/helpers/software_records_helper.rb

Resolves #203 
secret_key_base call to encrypt sensitive information field caused fatal runtime error. Update secret_key_base call as per https://stackoverflow.com/a/60712214

Update secret_key_base call for sensitive information field.

---

app/helpers/application_helper.rb
spec/factories/software_records.rb
spec/fixtures/software_records.csv
spec/helpers/application_helper_spec.rb

Resolves #228
Set initial count for graph to records existing prior to current year.

Fix software records graph

---

app/controllers/file_uploads_controller.rb

Mitigate command injection threat

---

config/deploy.rb

Add confirmation check for deploy

---

.rubocop.yml
app/assets/stylesheets/software_records.scss
app/controllers/software_records_controller.rb
app/models/software_record.rb
app/views/front/new.html.erb
app/views/layouts/application.html.erb
app/views/layouts/software_records.html.erb
app/views/software_records/_form_general.html.erb
app/views/software_records/_general.html.erb
db/migrate/20230503170052_add_admin_users_to_software_records.rb
db/schema.rb
exports/software_records.rb
load_records.rb
spec/controllers/front_controller_spec.rb
spec/controllers/software_records_controller_spec.rb
spec/load_records_spec.rb

Resolves #294 
Add admin_users serialized attribute to software_record.

Add admin users attribute to software record

---

config/brakeman.ignore

Ignore brakeman sql warnings

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/software_records.scss
app/assets/stylesheets/software_types.scss
app/assets/stylesheets/vendor_records.scss
app/views/file_uploads/new.html.erb

Changed values in requested areas including :
Grey Text in Menus
Red Text in Import Tool
Blue Text in Add More

240/Fixes some Accessibility Issues

---

scripts/start_qp.sh

Use puma as a service

---

scripts/check_ruby.sh

Add lines to ruby script to update versions available to rbenv.

---

Gemfile
Gemfile.lock

Bundler Audit flagged our version of nokogiri  >= 1.16.5
Fixes #365

Sets version of nokogiri in Gemfile

---

app/views/software_records/_general.html.erb
spec/views/software_records/show.html.erb_spec.rb

Fixes #335 
Adds simple_format to the app/views/software_records/_general.html.erb.
This allows for return carriages, line spacing, and style tagging.

Adds simple_format to notes field.

---

.github/workflows/main.yml
app/controllers/software_records_controller.rb
app/views/software_records/_form_maintenance_log.html.erb
app/views/software_records/_maintenance_log.html.erb
db/migrate/20250321143122_remove_latest_version_from_table_name.rb
db/schema.rb
spec/controllers/front_controller_spec.rb
spec/controllers/software_records_controller_spec.rb
spec/views/software_records/edit.html.erb_spec.rb
spec/views/software_records/edit_road_map.html.erb_spec.rb
spec/views/software_records/show.html.erb_spec.rb

This removes the Latest Version field from the application.

LIBAPPORT-59-Removes latest_version from application.

---

app/views/software_records/_form_maintenance_log.html.erb
app/views/software_records/_maintenance_log.html.erb
app/views/software_records/list_upgrades.html.erb
spec/controllers/software_records_controller_spec.rb
spec/views/software_records/edit.html.erb_spec.rb
spec/views/software_records/list_upgrades.html.erb_spec.rb

Updates the use of the priority field to use Low, Medium, and High.

LIBAPPORT-59 and LIBAPPORT-20 Priority

---

app/views/software_records/list_upgrades.html.erb
spec/views/software_records/list_upgrades.html.erb_spec.rb

Adds a field to the Maintenance List (list_upgrade.html.erb)

LIBAPPORT-51- Adds Planned Date to maintenance list.

---

exports/software_records.rb
spec/exports/software_records_spec.rb

Adds the Road Map Field to the Software Records Export

LIBAPPORT-65-Adds RoadMap Field to Export.

---

Gemfile
Gemfile.lock
app/controllers/export_data_controller.rb
exports/change_requests.rb
spec/controllers/export_data_controller_spec.rb
spec/exports/change_requests_spec.rb

This adds an exporter for Change Request.  We had the menu option, but didn't actually have an exporter.
I used the same strategy that we used with all of the other exporters.

LIBAPPPORT-63-Adds Change Request Exporter.
